2022-04-27 23:38:21,620 ERROR: Exception on /explore [GET] [in /home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/lordrambock/Python_Projects/Flask/microblog/app/routes.py", line 162, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "/home/lordrambock/Python_Projects/Flask/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lordrambock/Python_Projects/Flask/microblog/app/templates/index.html", line 28, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2022-04-27 23:39:03,096 INFO: Microblog startup [in /home/lordrambock/Python_Projects/Flask/microblog/app/__init__.py:46]
2022-04-30 11:42:33,679 INFO: Microblog startup [in /home/lordrambock/Python_Projects/Flask/microblog/app/__init__.py:52]
2022-04-30 13:14:24,769 INFO: Microblog startup [in /home/lordrambock/Python_Projects/Flask/microblog/app/__init__.py:52]
2022-04-30 20:22:21,417 INFO: Microblog startup [in /home/lordrambock/Python_Projects/Flask/microblog/app/__init__.py:52]
2022-05-05 19:21:54,659 INFO: Microblog startup [in /home/lordrambock/Python_Projects/Flask/microblog/app/__init__.py:52]
